name: Build Quarto site

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */23 * * *" # runs every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup-quarto@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
